"""Exact-support queue utilities.

For a positive integer x with prime support S, its exact-support queue is the
increasing sequence of positive integers whose prime support is exactly S.
The zero-based queue depth of x is therefore the number of smaller integers in
that queue.
"""

from __future__ import annotations

import heapq
from collections.abc import Iterator
from functools import lru_cache
from math import prod

from .decision import Support, prime_support


def iter_exact_support_queue(support: Support) -> Iterator[int]:
    """Yield the increasing exact-support queue for ``support``.

    For nonempty support S this is ``rad(S)`` times the multiplicative monoid
    generated by the primes of S. The empty support has the single value 1.
    """

    primes = tuple(sorted(support))
    if not primes:
        yield 1
        return

    radical = prod(primes)
    heap = [1]
    seen = {1}
    while heap:
        multiplier = heapq.heappop(heap)
        yield radical * multiplier
        for prime in primes:
            child = multiplier * prime
            if child not in seen:
                seen.add(child)
                heapq.heappush(heap, child)


@lru_cache(maxsize=None)
def _queue_value(primes: tuple[int, ...], depth: int) -> int:
    if depth < 0:
        raise ValueError("depth must be nonnegative")
    support = frozenset(primes)
    for current_depth, value in enumerate(iter_exact_support_queue(support)):
        if current_depth == depth:
            return value
    raise IndexError("exact-support queue is finite before requested depth")


def exact_support_queue_value(support: Support, depth: int) -> int:
    """Return the value at zero-based ``depth`` in an exact-support queue."""

    return _queue_value(tuple(sorted(support)), depth)


@lru_cache(maxsize=None)
def exact_support_queue_depth(value: int) -> int:
    """Return the zero-based rank of ``value`` in its exact-support queue.

    Equivalently, count the positive integers ``y < value`` with
    ``prime_support(y) == prime_support(value)``.
    """

    if value < 1:
        raise ValueError("value must be positive")

    primes = tuple(sorted(prime_support(value)))
    if not primes:
        return 0

    count = 0

    def visit(index: int, product: int) -> None:
        nonlocal count
        if index == len(primes):
            count += 1
            return

        prime = primes[index]
        next_product = product * prime
        while next_product < value:
            visit(index + 1, next_product)
            if next_product > (value - 1) // prime:
                break
            next_product *= prime

    visit(0, 1)
    return count
